---
title: "notebook2"
output: html_document
date: "2025-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load needed library}
# Load libraries
library(SingleCellExperiment)
library(slingshot)
library(Seurat)
library(ggplot2)
```

```{r}
#visually decide how many PCs to keep
ElbowPlot(OLOPC_19_fix, ndims = 40)
```

```{r}
#using 15 PCs causes clusters 3 and 0 to disappear from pseudotime trajectory
#17 PCs missing cluster 1
#20 PCs?
OLOPC_19_fix <- RunTSNE(OLOPC_19_fix, dims = 1:20)
```


```{r}
# Convert Seurat object to SingleCellExperiment, assign cluster labels
sce <- as.SingleCellExperiment(OLOPC_19_fix)
sce$cluster <- OLOPC_19_fix$seurat_clusters  # use Seurat cluster info
```

```{r}
#runs the Slingshot pseudotime
sce <- slingshot(sce, clusterLabels = 'cluster', reducedDim = 'TSNE')
```

```{r}
#Transfers the pseudotime values computed by Slingshot into Seurat object.
OLOPC_19_fix$pseudotime <- sce$slingPseudotime_1
```

```{r}
#Plots cells in t-SNE space, colored by pseudotime
FeaturePlot(OLOPC_19_fix, feature = "pseudotime", reduction = "tsne") +
  scale_color_viridis_c() +
  ggtitle("Pseudotime Progression (tSNE)") +
  theme_minimal()
```

```{r}
#add trajectory, but it did not visualized well
# Get tSNE coords
tsne_coords <- reducedDim(sce, "TSNE")

# Get curve data
curve_data <- slingCurves(sce)[[1]]

# Plot with curve
plot(tsne_coords, col = viridis::viridis(100)[cut(sce$slingPseudotime_1, 100)],
     pch = 16, asp = 1, main = "Slingshot Trajectory")
lines(curve_data, lwd = 2, col = 'black')
```
Want to add cluster label on the plot
```{r}
#converts t-SNE coordinates into a data frame
tsne_coords <- as.data.frame(tsne_coords)
colnames(tsne_coords) <- c("tSNE_1", "tSNE_2")

```


```{r}
#adds Slingshot pseudotime and cluster to each row cell
tsne_coords$pseudotime <- sce$slingPseudotime_1
tsne_coords$cluster <- sce$cluster
write.csv(tsne_coords, "tsne_coords.csv", row.names = TRUE)
```

```{r}
label_positions <- aggregate(cbind(tSNE_1, tSNE_2) ~ cluster, data = tsne_coords, FUN = mean)

```

```{r}
curve_list <- slingCurves(sce)

```

```{r}
tsne_coords <- reducedDim(sce, "TSNE")
tsne_df <- as.data.frame(tsne_coords)
colnames(tsne_df) <- c("tSNE_1", "tSNE_2")
tsne_df$pseudotime1 <- sce$slingPseudotime_1
tsne_df$cluster <- sce$cluster
pseudotime_mat <- slingPseudotime(sce)
tsne_df$avg_pseudotime <- rowMeans(pseudotime_mat, na.rm = TRUE)

```

```{r}
gg <- ggplot(tsne_df, aes(x = tSNE_1, y = tSNE_2, color = avg_pseudotime)) +
  geom_point(size = 1.2, alpha = 0.7) +
  scale_color_viridis(name = "Pseudotime", option = "D") +
  ggtitle("Multiple Slingshot Trajectories (tSNE)") +
  theme_minimal(base_size = 14)

# Add all trajectory lines
for (i in seq_along(curve_list)) {
  curve_i <- as.data.frame(curve_list[[i]]$s)
  colnames(curve_i) <- c("tSNE_1", "tSNE_2")
  gg <- gg + geom_path(data = curve_i, aes(x = tSNE_1, y = tSNE_2),
                       color = "black", size = 1.2)
}

gg

```
```{r}
label_positions <- aggregate(cbind(tSNE_1, tSNE_2) ~ cluster, data = tsne_df, FUN = mean)
gg <- gg + geom_text_repel(data = label_positions,
                           aes(x = tSNE_1, y = tSNE_2, label = cluster),
                           size = 5, color = "black", fontface = "bold")
gg
```


