 ---
title: "notebook3"
output: html_document
date: "2025-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load needed library}
# Load libraries
library(SingleCellExperiment)
library(slingshot)
library(Seurat)
library(ggplot2)
```

```{r}
#visually decide how many PCs to keep
ElbowPlot(OLOPC_19_subs, ndims = 40)
```

```{r}
#base on the ElbowPlot, 15 might be a good choice?
OLOPC_19_subs <- RunTSNE(OLOPC_19_subs, dims = 1:17)
```


```{r}
# Convert Seurat object to SingleCellExperiment, assign cluster labels
sce <- as.SingleCellExperiment(OLOPC_19_subs)
sce$cluster <- OLOPC_19_subs$seurat_clusters  # use Seurat cluster info
```

```{r}
reducedDims(sce)$TSNE <- OLOPC_19_fix@reductions$tsne@cell.embeddings
```


```{r}
#runs the Slingshot pseudotime
sce <- slingshot(sce, clusterLabels = 'cluster', reducedDim = 'TSNE')
```

```{r}
#Transfers the pseudotime values computed by Slingshot into Seurat object.
OLOPC_19_subs$pseudotime <- sce$slingPseudotime_1
```

```{r}
#Plots cells in t-SNE space, colored by pseudotime
FeaturePlot(OLOPC_19_subs, feature = "pseudotime", reduction = "tsne") +
  scale_color_viridis_c() +
  ggtitle("Pseudotime Progression (tSNE)") +
  theme_minimal()
```

```{r}
#add trajectory, but it did not visualized well
# Get tSNE coords
tsne_coords <- reducedDim(sce, "TSNE")

# Get curve data
curve_data <- slingCurves(sce)[[1]]

# Plot with curve
plot(tsne_coords, col = viridis::viridis(100)[cut(sce$slingPseudotime_1, 100)],
     pch = 16, asp = 1, main = "Slingshot Trajectory")
lines(curve_data, lwd = 2, col = 'black')
```
Want to add cluster label on the plot
```{r}
#converts t-SNE coordinates into a data frame
tsne_coords <- as.data.frame(tsne_coords)
colnames(tsne_coords) <- c("tSNE_1", "tSNE_2")

```

```{r}
#adds Slingshot pseudotime and cluster to each row cell
tsne_coords$pseudotime <- sce$slingPseudotime_1
tsne_coords$cluster <- sce$cluster
write.csv(tsne_coords, "tsne_coords.csv", row.names = TRUE)
```

```{r}
label_positions <- aggregate(cbind(tSNE_1, tSNE_2) ~ cluster, data = tsne_coords, FUN = mean)

```

```{r}
curve_list <- slingCurves(sce)

```

```{r}
tsne_coords <- reducedDim(sce, "TSNE")
tsne_df <- as.data.frame(tsne_coords)
colnames(tsne_df) <- c("tSNE_1", "tSNE_2")
tsne_df$pseudotime1 <- sce$slingPseudotime_1
tsne_df$cluster <- sce$cluster
pseudotime_mat <- slingPseudotime(sce)
tsne_df$avg_pseudotime <- rowMeans(pseudotime_mat, na.rm = TRUE)

```

```{r}
library(viridis)
gg <- ggplot(tsne_df, aes(x = tSNE_1, y = tSNE_2, color = avg_pseudotime)) +
  geom_point(size = 1.2, alpha = 0.7) +
  scale_color_viridis(name = "Pseudotime", option = "D") +
  ggtitle("Multiple Slingshot Trajectories (tSNE)") +
  theme_minimal(base_size = 14)

# Add all trajectory lines
for (i in seq_along(curve_list)) {
  curve_i <- as.data.frame(curve_list[[i]]$s)
  colnames(curve_i) <- c("tSNE_1", "tSNE_2")
  gg <- gg + geom_path(data = curve_i, aes(x = tSNE_1, y = tSNE_2),
                       color = "black", size = 1)
}

gg

```
```{r}
#trajectory using number label of the clusters
library(shadowtext)

label_positions <- aggregate(cbind(tSNE_1, tSNE_2) ~ cluster, data = tsne_df, FUN = mean)
gg <- gg + shadowtext::geom_shadowtext(
    data = label_positions,
    aes(x = tSNE_1, y = tSNE_2, label = cluster),
    size = 5,
    color = "black",
    bg.color = "white", 
    fontface = "bold")
gg
```

```{r}
#rowname is the condition in tsne_df, format as e.g.tamA_AAAAAAAGGTTGGTTA
#filter
tsne_df$condition <- sub("_.*", "", rownames(tsne_df))

# used dictionary to map the standard condition given in OLOPC_19_subs
tsne_df$condition_grouped <- dplyr::case_when(
  grepl("^bex", tsne_df$condition) ~ "bex",
  grepl("^cpz", tsne_df$condition) ~ "cpz",
  grepl("^naive", tsne_df$condition) ~ "naive",
  grepl("^tam", tsne_df$condition) & !grepl("tambex", tsne_df$condition) ~ "tam",
  grepl("^tambex1wk", tsne_df$condition) ~ "tambex1wk",
  grepl("^tambex", tsne_df$condition) ~ "tambex",
  grepl("^veh1wk", tsne_df$condition) ~ "veh1wk",
  grepl("^veh", tsne_df$condition) ~ "veh",
  TRUE ~ "other"
)
```

```{r}
#plot condition tSNE plot with many colors
ggplot(tsne_df, aes(x = tSNE_1, y = tSNE_2, color = condition_grouped)) +
  geom_point(size = 0.7, alpha = 0.6) +
  theme_minimal(base_size = 14) +
  ggtitle("tSNE Plot Colored by Condition") +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.title = element_text(face = "bold")
  ) +
  scale_color_brewer(palette = "Set1")

```


```{r}

conditions <- unique(tsne_df$condition_grouped)
#write a function to plot 1 condition at a time, other conditions in grey
plots <- lapply(conditions, function(cond) {
  tsne_df %>%
    dplyr::mutate(color_flag = ifelse(condition_grouped == cond, cond, "Other")) %>%
    ggplot(aes(x = tSNE_1, y = tSNE_2)) +
    
    # First draw grey background
    geom_point(data = ~subset(., color_flag == "Other"), color = "grey80", size = 1.2, alpha = 0.5) +
    
    # Then draw colored condition on top
    geom_point(data = ~subset(., color_flag == cond), color = "blue", size = 1.2, alpha = 0.9) +

    theme_minimal(base_size = 14) +
    ggtitle(paste("tSNE Condition Plot -", cond)) +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "none"
    )
})

```

#showing plots format in print(plots[[index]])

```{r}
print(plots[[1]])

```





```{r}
print(plots[[2]])
```
```{r}
print(plots[[3]])

```
```{r}
print(plots[[4]])

```

```{r}
print(plots[[5]])

```

```{r}
print(plots[[6]])

```
```{r}
print(plots[[7]])
```
```{r}
print(plots[[8]])

```

```{r}
#required genes expression for colored plots
genes_to_plot <- c("Il33", "Mal", "Apod", "Daam2", "Ankub1", "Plekhh1", "Adipor2")

#write a function to plot
plots <- lapply(genes_to_plot, function(gene) {
  FeaturePlot(
    OLOPC_19_subs,
    features = gene,
    reduction = "tsne",
  ) +
    scale_color_gradient(low = "grey95", high = "darkblue", limits = c(0, 5))+
    ggtitle(paste(gene, "Expression on tSNE")) +
    theme_minimal(base_size = 16)
})

```

```{r}
print(plots[[1]])
```
```{r}
print(plots[[2]])
```
```{r}
print(plots[[3]])
```

```{r}
print(plots[[4]])
```

```{r}
print(plots[[5]])
```
```{r}
print(plots[[6]])
```
```{r}
print(plots[[7]])

```
```{r}
print(plots[[8]])

```




